{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "szca-media-gateway.fullname" . }}
  labels:
    {{- include "szca-media-gateway.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ include "szca-media-gateway.fullname" . }}-secrets
    creationPolicy: Owner
  dataFrom:
    {{- toYaml .Values.externalSecret.dataFrom | nindent 4 }}
{{- end }}
